#######################
# General Configuration
#######################
language: java
sudo: false
dist: xenial
jdk:
  - openjdk8
os:
  - linux


install: true

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: change
    rooms:
      - vaader-ietr:EEtUq0RrGRpHSXWZiEApSDwS#preesm

addons:
  sonarcloud:
    organization: "preesm"
    token:  
      secure: "ph8Qd998uGCP9NRRqMFBiM4FJJIl/IfsQvTkJNUk+7PTFn8HW0TcwbCHyFM0G4EmuLHHbiqjFwJH8Zju3c+jfIMF0b4hPdDebDiLXvFgOy0/48mAA3w53228JUqMGrHL7YzH4l0GeEILT+ugQ3P4OfvHPI4Mq2bA5iHZQR9kHDlHohbPxD3z3nFkXuMvxHItXkNGdFv+ymZ+RRbTEuU4VuioICLHmeY7JJHdv4KD7UmC+Ob68RVTBsuxjpSniEEIpBfzHF+Uw0lJLfEIH721piAVToaiVrWlQa08+VsUfOG6PdwQ9QILdxVjTO24aGReYBwZ1G5p1NRDzYdx9/Y4zniHhCDAoaWAz0XUjiKMmVArZZdDgBUSCHDNKXLVrGzxFLlvt3cBTcPO8yH3ULQh67f+Vj9+2BQHvs9sme788YPBzJ+OnjWW907+SiACNrm0rvDah9sjAwhEvSoUpVquhdbGzIwKOsjubyHFVpF8974EIz4mgcTjqj4qF7ChwMyFoZraiIRWHAN7vmE+VV1NW5SoHye0wzi8YSPdPBt3qPi15pBSrFU4la5d4sUv4TzQmA9SMA65xfNfJB7phregZRC9TFMk+7KZ2Y0P5dE2u7GiTlyAtJZJOjGtO1JcXP02eP4FZWmmSkJYj2l11KgRxUUKPv/5ADRTaIiu/FWDjTc="


script: 
  - git fetch --unshallow --quiet
  - if [ "$TRAVIS_BRANCH" != "master" ]; then git fetch --no-tags https://github.com/$TRAVIS_REPO_SLUG.git +refs/heads/master:refs/remotes/origin/master ;fi
  - ./releng/build_and_test.sh



#https://docs.travis-ci.com/user/deployment/pages/
# GITHUB_TOKEN is set in https://travis-ci.org/m2e-code-quality/m2e-code-quality/settings
# see https://github.com/m2e-code-quality/m2e-code-quality/issues/123
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: new-site
    repo: preesm/preesm-snapshot-site
    target_branch: gh-pages
    on: 
      branch: develop

before_deploy: ./releng/snapshot_predeploy.sh
